// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGNBinM4SNWhIK7qeyHBkZobt_k2-xC94',
    appId: '1:732648543361:web:a53ef5553c720180ca2980',
    messagingSenderId: '732648543361',
    projectId: 'quick-marble-ac58f',
    authDomain: 'quick-marble-ac58f.firebaseapp.com',
    storageBucket: 'quick-marble-ac58f.firebasestorage.app',
    measurementId: 'G-ZKR8Z8MQET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3G9ZjssDY9vYxj5DjD-yKiXkcMF0DeHQ',
    appId: '1:732648543361:android:f88323422763cc0aca2980',
    messagingSenderId: '732648543361',
    projectId: 'quick-marble-ac58f',
    storageBucket: 'quick-marble-ac58f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdPWZEsdur_B2HQ_PPdGUamluAyAQMB1E',
    appId: '1:732648543361:ios:a11859eeab3d9d0eca2980',
    messagingSenderId: '732648543361',
    projectId: 'quick-marble-ac58f',
    storageBucket: 'quick-marble-ac58f.firebasestorage.app',
    iosClientId: '732648543361-nbtd8ebjo9u1b477anrck24shlidvi41.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickMarble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdPWZEsdur_B2HQ_PPdGUamluAyAQMB1E',
    appId: '1:732648543361:ios:a11859eeab3d9d0eca2980',
    messagingSenderId: '732648543361',
    projectId: 'quick-marble-ac58f',
    storageBucket: 'quick-marble-ac58f.firebasestorage.app',
    iosClientId: '732648543361-nbtd8ebjo9u1b477anrck24shlidvi41.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickMarble',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGNBinM4SNWhIK7qeyHBkZobt_k2-xC94',
    appId: '1:732648543361:web:c87a5b9b1e44f140ca2980',
    messagingSenderId: '732648543361',
    projectId: 'quick-marble-ac58f',
    authDomain: 'quick-marble-ac58f.firebaseapp.com',
    storageBucket: 'quick-marble-ac58f.firebasestorage.app',
    measurementId: 'G-WNJRNG0Q1X',
  );
}
